// Create a new GUI window
f = figure('figure_name', 'My Interface', ...
           'position', [0, 0, 1920, 1080]);

// Add a push button with a click callback
uicontrol('parent', f, ...
          'style', 'pushbutton', ...
          'string', 'Click Me', ...
          'position', [65, 70, 100, 40], ...
          'callback', 'messagebox([''You clicked the button!''], ''Info'')');
